# Site settings
author: Achsah M.
title: Achsah Everyday
header-img: img/home-bg.png
email: achsahmp@gmail.com
copyright_name: Achsah M.
description: > # this means to ignore newlines until "baseurl:"
  Achsah Codes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  achsahmerina

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
